# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 747468e3a8a1b8aca9c9b6648a39b4ab03cc145f21d3d28228ccf6211927c98ba18114fa0d1b1a64bd28706a638096d85d1bb145d93fc142fe90523d789e53d8

test:
  secret_key_base: 9f35a1c4bb81833ac449c862ea1a7985581bb2d0d8f5cf230b194793e4ecad9b3ee5a974c0f4ab51b335a02e176d4197ad3d2363efa8493f50b3ff430ca2855e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
